### ISSUE TITLE
Debug mocha test units

### ISSUE THREAD

**Issue by rmemoria** [middleware-io/gulp-node-debug#1]
Thanks for the plugin... Great work (even wrapping node-inspector, it makes debugging easier).

Wondering if there is a way to debug a test unit (in my case I use mocha).

Thanks,
Ricardo

**Comment by rmemoria** [comment]
Sorry... Just saw the instructions in the readme file. But after following that, I still can't debug:

I had to make some adjustments:

``` javascript
    var mochaScript = 'node_modules/mocha/bin/_mocha';

gulp.src([mochaScript])
    .pipe(nodeDebug({
        debugBrk: true,
        script: ['server/test/**/*.js', '--watch'],
    }));
```

Because of the --watch param, the test is re-run whenever I change the source file, but breakpoints are ignored in Chrome editor.

Any tip???

Thanks again,
Ricardo

**Comment by JohannesHoppe** [comment]
Hi,

great to hear that you like the plugin. The example in the readme implies that you want to use the default test directory (which is “./test”). If you do not have errors, everything should be fine.

I can confirm that the node-inspector can be tricky to use. Try to use the latest version of node.js. Sometimes it displays the correct file, but it’s not visible that you are actually debugging that file. (no breakpoints can be set, no indicator for the current line). If this happens, press F11 to step into.

Sometimes node-inspector is even pickier. The ultimate solution is a “debugger” statement in your debugged script and/or the unit-test itself.

I hope that helps. Please report if this was solving you issues!

Greets,
Johannes

**Comment by JohannesHoppe** [comment]
Btw, you might be interested in that gulpfile, which has some more examples:
https://github.com/middleware-io/middleware.io/blob/master/gulpfile.js

**Comment by JohannesHoppe** [comment]
Latest npm package includes that readme text now.
