### ISSUE TITLE
Doesn't install on Node 4

### ISSUE THREAD

**Issue by mettjus** [middleware-io/gulp-node-debug#3]
Gives error when trying to install on Node 4.
- node v4.0.0
- npm v2.14.2

**Comment by JohannesHoppe** [comment]
Could you post the error message, too?

**Comment by aronrodrigues** [comment]
Same here.
Window, Node4, npm 2.14.2
No python.

**Comment by aronrodrigues** [comment]
C:\Users\aronrodrigues\workspaces\afrgree>npm install gulp-node-debug
npm WARN optional dep failed, continuing default-browser-id@1.0.2
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.1.0","npm":"2.14.3"})

> v8-debug@0.4.6 preinstall C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug
> 
> v8-profiler@5.2.12 preinstall C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler
> 
> bufferutil@1.1.0 install C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> utf-8-validate@1.1.0 install C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\ws\node_modules\utf-8-validate
ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
/

> v8-debug@0.4.6 install C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )

C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-x64\debug.node --module_name=debug --module_path=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-x64 )  else (node  configure --fallback-to-build --module=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-x64\debug.node --module_name=debug --module_path=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-x64\debug.node" "--module_name=debug" "--module_path=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-x64"
gyp ERR! cwd C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-x64\debug.node --module_name=debug --module_path=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug
node-pre-gyp ERR! node -v v4.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-x64\debug.node --module_name=debug --module_path=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-x64' (1)

> v8-profiler@5.2.12 install C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler
> node-pre-gyp install --fallback-to-build

C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )

C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-x64 )  else (node  configure --fallback-to-build --module=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-x64\profiler.node" "--module_name=profiler" "--module_path=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-x64"
gyp ERR! cwd C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler
node-pre-gyp ERR! node -v v4.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\aronrodrigues\workspaces\afrgree\node_modules\gulp-node-debug\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v46-win32-x64' (1)
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "gulp-node-debug"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\aronrodrigues\workspaces\afrgree\npm-debug.log

**Comment by JohannesHoppe** [comment]
According to the log this is a node-gyp issue.
1. First problem: Python 2.x is not installed. Python is a must have, same for the compiler which comes with Visual Studio. see: https://github.com/nodejs/node-gyp You will get the same error with a lot of other npm packages which depend on compiled code. Hint: https://github.com/Microsoft/nodejstools is a no-brainer.
2. Also there is an open issue on node-gyp: https://github.com/nodejs/node-gyp/issues/736 ("Is node-gyp supposed to work with node 4.0/4.1")

I will watch on #736. Right now I recomment to not use nodejs 4.0 (on windows).

**Comment by jd-carroll** [comment]
Any update on this?

**Comment by JohannesHoppe** [comment]
Nope, sorry. I'm completely busy doing stuff.

I personally switched to [VSCode](https://code.visualstudio.com/). It has an awesome node.js debugger. You should give it a try:
https://code.visualstudio.com/Docs/editor/debugging

**Comment by jd-carroll** [comment]
I am using code, but how would I attach the debugger when running gulp?

**Comment by JohannesHoppe** [comment]
Do you struggle to debug the gulp script or do you want to debug the final output of that gulp script?
Both is easy to set up if you play around wit the `launch.json`.

**Comment by jd-carroll** [comment]
I am trying to debug the gulp script itself (trying to write a new plugin).  I've added something like this to the launch.json:

```
            "program": "${workspaceRoot}/lambdas/alert-api/alert-create/gulpfile.js",
            "stopOnEntry": false,
            "args": ["pacakge"],
            "cwd": "${workspaceRoot}/lambdas/alert-api/alert-create",
```

And within the gulpfile.js there is a task such as:

```
gulp.task('package', function() { ... }
```

However, package isn't being invoked when run from code debugger

**Comment by JohannesHoppe** [comment]
https://hansrwindhoff.wordpress.com/2015/05/05/debugging-task-runner-tasks-like-gulp-with-visual-studio-code-editordebugger/

also, you have a typo at `pacakge`

**Comment by JohannesHoppe** [comment]
## This project is not maintained anymore. The code does not run on node 4+ and I don't have time and moot to fix that.

[I reommend the debugger from Visual Studio Code as a great replacement:](https://code.visualstudio.com/docs/editor/debugging)
[![Screenshot](https://raw.githubusercontent.com/wiki/middleware-io/gulp-node-debug/debugging_hero.png)](https://code.visualstudio.com/docs/editor/debugging)
